name: webview_flutter
description: A Flutter plugin that provides a WebView widget on Android and iOS.
version: 2.0.1


environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewFlutterPlugin
      ios:
        pluginClass: FLTWebViewFlutterPlugin
